
% Real-time kernel repeater
% Reads UDP packets from the tracker stream, evaluates the calibrated PCA
% kernel at the current hand position, and updates a normalized control value.

close all
clear
clc

addpath("functions\")

%% Initialization

% Load the calibration output generated by mainCalibration_AUTO.m.
load pcaClusteredValues.mat

kernel = 0;
controlValue = 0;
actual_position = 0;
timestamp = 0;

%% Main Loop

% Open the UDP listener used for incoming tracker data.
tracker_udp = udpport("datagram","LocalPort",8051);

% For plotting real time control values
controlValue_plot = [];

hFigure = figure(); % Figure used to display the control trace.
setappdata(hFigure, 'signMultiplier', 1);

MessageBox = msgbox( 'Stop DataStream', 'Kinematic Null Space' );

% Button used to flip the sign of the incremental control update.
hButtonSign = uicontrol('Style', 'pushbutton', 'String', 'Change Sign', ...
    'Position', [20 20 100 40], 'Callback', @changeSign);

prev_max_ker = []; % Initialize empty at the start
prev_min_ker = []; % Initialize empty at the start
prev_PC_coeff = []; % Initialize empty at the start
prev_PC_mu = []; % Initialize empty at the start

controlValue_saved = [];

load task_example.mat


while(ishandle(MessageBox))
    
    if tracker_udp.NumDatagramsAvailable > 0
        % Read the next packet and keep the previous timestamp for a simple
        % sample-time estimate.
        data = read(tracker_udp,tracker_udp.DatagramsAvailableFcnCount);
        timestamp_old = timestamp;
        
        % Unpack the raw UDP payload into timestamp, tracker count, and data.
        [td,timestamp, numTrackers] = unpackData(data.Data);
        dati = [timestamp numTrackers reshape(td',1,[])];
        
        % Re-express all tracker positions relative to the chest tracker frame.
        numActiveTracker = dati(2);
        
        chest_pos = dati(end-6:end-4);
        chest_orientation = conj(quaternion(dati(:,end-3:end)));
        
        for i = 1:numActiveTracker
            tracked_data_world = dati (:,(3+(i-1)*7 : 5+(i-1)*7) ) - chest_pos;
            tracked_data_chest = rotatepoint(chest_orientation,tracked_data_world);
            dati (:,(3+(i-1)*7 : 5+(i-1)*7) ) = tracked_data_chest;
        end
        
        % Convert the packet back into one row per tracker.
        data = reshape(dati(3:end),[],numActiveTracker)';  % row = x, y, z, quaternion(w, x, y, z)
        
        % Extract the relative quaternion signal used by the PCA kernel.
        quatRelative = getRelativeRotation(data); % n rows, n = numtracker
        quatRelative  = [quatRelative(:).compact];
        quatRelativeLine = reshape(quatRelative', 1, []);
        
        actual_position = data(1,1:3);
        
        % Interpolate the kernel parameters at the current hand position.
        max_ker =   computeKernelInterpolationMatrices(kernel_coordinates,kernel_max_values, actual_position, prev_max_ker);
        min_ker =   computeKernelInterpolationMatrices(kernel_coordinates,kernel_min_values, actual_position, prev_min_ker);
        PC_coeff =  computeKernelInterpolationMatrices(kernel_coordinates,kernel_coeff_values, actual_position, prev_PC_coeff);
        PC_mu =  computeKernelInterpolationMatrices(kernel_coordinates,mu_all, actual_position, prev_PC_mu);
        
        prev_max_ker = max_ker;
        prev_min_ker = min_ker;
        prev_PC_coeff = PC_coeff;
        prev_PC_mu = PC_mu;
        
        % Project the current orientation onto the local calibrated PCA basis.
        kernel_ = (quatRelativeLine-PC_mu)*PC_coeff';
        
        kernel_old = kernel;
        kernel = (kernel_-min_ker)/(max_ker-min_ker);
        
        % Apply the incremental update and allow the sign toggle button to flip it.
        kernel_dt = kernel-kernel_old;
        
        signMultiplier = getappdata(hFigure, 'signMultiplier');
        controlValue = controlValue + signMultiplier * kernel_dt;
        
        % Clamp the control signal to the [0, 1] range.
        if controlValue > 1
            controlValue = 1;
        elseif controlValue < 0
            controlValue = 0;
        end
        
        controlValue_saved(end+1) = controlValue;
        
        % Store only the last 400 values.
        controlValue_plot = [controlValue_plot, controlValue];
        if length(controlValue_plot) > 400
            controlValue_plot = controlValue_plot(end-399:end);
        end
        
        % Update the live plot.
        plot(controlValue_plot, 'LineWidth', 3)
        xlim([0, 600]) % Set the x-axis window to 600
        ylim([-0.1, 1.1])
        drawnow;
    end
    pause(0.001);
end

flush(tracker_udp,"input")
% flush(send_udp,"output")

% clear send_udp
clear tracker_udp

